### ISSUE TITLE
Auto pool income distribution not working

### ISSUE THREAD

**Issue by hustynetwork** [hustynetwork/Nuvizion#13]

**Comment by akram37460** [comment]
Done

**Comment by hustynetwork** [comment]
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/52190386/194814357-dd1e3e67-3992-49e8-b116-bfd217f9b0e1.png">
Still showing $12 grouped income. Suppose to show $6 for every payment received in the auto pool matrix

**Comment by akram37460** [comment]
Please sir explain what is wronge
